### ISSUE TITLE
chai smoothie install throw error

### ISSUE THREAD

**Issue by vijay-kumar-singh** [jan-molak/chai-smoothie#5]
installing chai smoothie throw error
npm install chai-smoothie --save-dev

```
├── UNMET PEER DEPENDENCY chai@4.0.2
├── chai-smoothie@0.3.1 
└── UNMET PEER DEPENDENCY tsutils@1.6.0
```

```
npm WARN chai-smoothie@0.3.1 requires a peer of chai@>= 3.0.0 < 4 but none was installed.
npm WARN tslint-microsoft-contrib@5.0.0 requires a peer of tsutils@1.6.0 but none was installed.
```

My package.json devDependencies:

```
"devDependencies": {
    "@types/chai": "4.0.0",
    "@types/chai-as-promised": "0.0.31",
    "@types/cucumber": "1.3.1",
    "@types/node": "7.0.31",
    "chai": "4.0.2",
    "chai-as-promised": "7.0.0",
    "chai-smoothie": "^0.3.1",
    "cucumber": "1.3.2",
    "npm-failsafe": "0.x",
    "protractor": "5.1.2",
    "rimraf": "2.6.1",
    "serenity-cli": ">= 0.4.0",
    "serenity-js": ">= 1.7.0",
    "ts-node": "3.0.6",
    "tslint": "5.4.3",
    "tslint-microsoft-contrib": "5.0.0",
    "typescript": "2.4.0"
  },
```

is chai-smoothie does not support chai version 4? Also please suggest to fix UNMET PEER DEPENDENCY tsutils@1.6.0 issue.

Regards,
Vijay

**Comment by jan-molak** [comment]
Hey Vijay!

Yes, chai-smoothie has a [peer dependency](https://nodejs.org/en/blog/npm/peer-dependencies/) on chai. 
To address the problem with the missing peer dependency you should install that one too:

```
npm install --save-dev chai@3.x chai-smoothie
```

I didn't have a chance to test smoothie with Chai version 4, that's why the range is specified as `>= 3.0.0 < 4`. If you'd like to help out with testing smoothie against Chai v.4 please let me know!

I'm not sure where the problem with `tslint-microsoft-contrib` and `tsutils` is coming from, I'm afraid. Those are not the dependencies of `chai-smoothie`, so perhaps the warning comes from another modules you have installed?

Jan

**Comment by vijay-kumar-singh** [comment]
Hi Jan,
I have installed chai-smoothie 3.x as per your suggestion.
Installation was successful. But still i am not able to use chai-smoothie syntax.
**Please refer below package.json config:**
_"devDependencies": {
    "@types/chai": "3.4.35",
    "@types/chai-as-promised": "0.0.31",
    "@types/cucumber": "1.3.1",
    "@types/node": "7.0.31",
    "chai": "^3.5.0",
    "chai-as-promised": "7.0.0",
    "chai-smoothie": "^0.3.1",
    "cucumber": "1.3.2",
    "npm-failsafe": "0.x",
    "protractor": "5.1.2",
    "rimraf": "2.6.1",
    "serenity-cli": ">= 0.4.0",
    "serenity-js": ">= 1.7.0",
    "ts-node": "3.0.6",
    "typescript": "2.4.0"
  },_
**Feature Step code:**
 _this.Then(/(.*) should be shown$/, function(details) {
        return actor.attemptsTo(
            expect(actor.toSee(WebElement.of(FlyingBlueUI.Booking_Code_Label))).displayed,
        );
    });_
**expect.ts**
import chai = require('chai');
import chaiAsPromised = require('chai-as-promised');
import chaiSmoothie = require('chai-smoothie');

chaiAsPromised.transformAsserterArgs = args => Promise.all(args)

chai.use(chaiAsPromised);
chai.use(chaiSmoothie);

export const expect = chai.expect;
**Error: 
Argument of type 'Assertion' is not assignable to parameter of type 'Activity'.**

Could you please help me to solve this?

Regards,
Vijay Singh
