### ISSUE TITLE
TypeScript typings are missing chai-as-promised integration

### ISSUE THREAD

**Issue by InvictusMB** [jan-molak/chai-smoothie#6]
The code from example `expect(element(by.id('title'))).to.eventually.be.displayed` produces the following TS compiler error:
```
Error:(1, 50) TS2339:Property 'displayed' does not exist on type 'PromisedAssertion'.
```
Versions:
```
    "@types/chai": "3.4.35",
    "@types/chai-as-promised": "0.0.31",
    "chai": "^3.5.0",
    "chai-as-promised": "7.0.0",
    "chai-smoothie": "^0.3.1",
    "typescript": "2.4.0"
```

Patching the `lib/chai-smoothie.d.ts` to extend the `Chai.Eventually` with the following annotation fixed the compiler error. 
```
interface Eventually {
    displayed: PromisedAssertion;
    present: PromisedAssertion;
    enabled: PromisedAssertion;
    selected: PromisedAssertion;
    text(text: string): PromisedAssertion;
}
```
I don't know the code of chai or chai-as-promised to tell if that fix reflects the run time types properly though.

**Comment by InvictusMB** [comment]
Added a PR to fix this. 
Also the TypeScript setup of the package seems outdated. I get 25 errors when transpiling the code. That is not breaking the build though (see Travis output).

I've tried updating protractor and TS compiler version and replacing typings setup with `@types` but that is a rabbit hole of updating all the deps and configs.

**Comment by jan-molak** [comment]
Awesome, thanks @InvictusMB!
