### ISSUE TITLE
isdiplayed not working 

### ISSUE THREAD

**Issue by seshu727** [jan-molak/chai-smoothie#9]

**Comment by jan-molak** [comment]
Hi @seshu727 - would you be able to provide me with a bit more context and ideally a [test](https://github.com/jan-molak/chai-smoothie/blob/master/spec/e2e/chai-smoothie.spec.ts) showing under what circumstances `isDisplayed` is not working?

Thank you!
Jan

**Comment by jan-molak** [comment]
Hey @seshu727, since I haven't heard from you in a while I'm closing the ticket. Please feel free to open another ticket should you find that there's a defect in `isDisplayed`
